### ISSUE TITLE
property pro dobu trvani v mesicich

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opendatacz/public-contracts-ontology#1]
```
Chybí nám property durationMonths pro zaznamenání doby trvání zakázky v 
měsících (máme pouze durationDays).
```

Original issue reported on code.google.com by `martinnec@gmail.com` on 27 Jul 2012 at 10:11

**Comment by jindrichmynarz** [comment]
The `pc:duration`'s `rdfs:range` is `xsd:duration`, which is can express duration in months as well.
