### ISSUE TITLE
Cannot find property pc:supplier

### ISSUE THREAD

**Issue by giuseppefutia** [opendatacz/public-contracts-ontology#2]
Hi guys,

I want to use your ontology in my research project, but I cannot find the "pc:supplier" property in your RDF file (https://github.com/opendatacz/public-contracts-ontology/blob/master/public-contracts.ttl), as instead described in the UML schema (https://github.com/opendatacz/public-contracts-ontology/blob/master/diagrams/public-contracts-uml.png).

Could you help me?

Thanks for your attention,

Best,

Giuseppe

**Comment by jindrichmynarz** [comment]
Based on our previous discussions with domain experts `pc:supplier` was replaced by `pc:bidder` in the current version of the ontology. Unfortunately the UML diagram isn't up-to-date.

**Comment by giuseppefutia** [comment]
Thank you for the information!
